# PyLiRP Configuration - Client Only Mode
# Connects to remote services without port conflicts

serial:
  port: /dev/ttyUSB0  # Change to your serial port
  baudrate: 115200
  flow_control: hardware  # none/hardware/software
  timeout: 5.0
  write_timeout: 2.0

network:
  local_ip: 10.0.0.2    # This client's PPP IP
  remote_ip: 10.0.0.1   # Remote host's PPP IP
  mtu: 1500
  netmask: 255.255.255.0

ppp:
  lcp_echo_interval: 30
  lcp_echo_failure_threshold: 3
  max_configure_requests: 10
  restart_timeout: 3
  negotiate_magic: true
  negotiate_mru: true
  negotiate_compression: true
  default_mru: 1500
  magic_number: null

tcp:
  initial_window_size: 8192
  max_window_size: 65535
  mss: 1460
  retransmission_timeout_min: 200
  retransmission_timeout_max: 60000
  max_retransmissions: 5
  keepalive_interval: 7200
  keepalive_probes: 9
  keepalive_probe_interval: 75
  time_wait_timeout: 120
  congestion_algorithm: reno
  initial_cwnd: 10
  slow_start_threshold: 65535
  duplicate_ack_threshold: 3

services:
  # CLIENT MODE: Map remote services to non-conflicting local ports
  22: 
    host: 127.0.0.1
    port: 2222        # Remote SSH → local port 2222
    name: Remote-SSH
    enabled: true
    max_connections: 10
    connection_timeout: 300
  
  80:
    host: 127.0.0.1
    port: 8080        # Remote HTTP → local port 8080
    name: Remote-HTTP
    enabled: true
    max_connections: 50
    connection_timeout: 60
    
  443:
    host: 127.0.0.1
    port: 8443        # Remote HTTPS → local port 8443
    name: Remote-HTTPS
    enabled: true
    max_connections: 50
    connection_timeout: 120
    
  3389:
    host: 127.0.0.1
    port: 13389       # Remote RDP → local port 13389
    name: Remote-RDP
    enabled: false
    max_connections: 5
    connection_timeout: 300
    
  5900:
    host: 127.0.0.1
    port: 15900       # Remote VNC → local port 15900
    name: Remote-VNC
    enabled: false
    max_connections: 3
    connection_timeout: 300
    
  # Additional common services
  25:
    host: 127.0.0.1
    port: 2525        # Remote SMTP → local port 2525
    name: Remote-SMTP
    enabled: false
    max_connections: 10
    connection_timeout: 60
    
  110:
    host: 127.0.0.1
    port: 2110        # Remote POP3 → local port 2110
    name: Remote-POP3
    enabled: false
    max_connections: 10
    connection_timeout: 60

proxy:
  type: none
  host: 127.0.0.1
  port: 1080
  username: null
  password: null
  connection_timeout: 10
  enabled: false

security:
  allowed_ports: [22, 80, 443, 3389, 5900, 25, 110, 993, 995]
  blocked_ips: []
  rate_limiting:
    enabled: true
    connections_per_second: 10
    burst_size: 20
    window_size: 60
  
  connection_limits:
    global_max_connections: 200
    per_service_max: 50
    per_ip_max: 20
  
  log_security_events: true
  log_rejected_connections: true
  log_rate_limit_violations: true

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  
  file:
    enabled: true
    path: /var/log/pyslirp/pyslirp.log
    max_size: 10MB
    rotate_count: 5
  
  console:
    enabled: true
    color: true
  
  components:
    ppp: INFO
    tcp: INFO
    serial: INFO
    proxy: INFO
    security: INFO
    metrics: INFO

monitoring:
  enable_metrics: true
  metrics_port: 9090
  metrics_path: /metrics
  
  health_check:
    enabled: true
    port: 9091
    path: /health
    
  packet_capture:
    enabled: false
    pcap_file: /var/log/pyslirp/pyslirp.pcap
    max_file_size: 100MB
    rotate_files: true
    
  performance:
    track_connection_stats: true
    track_bandwidth: true
    track_latency: true
    stats_interval: 30

error_recovery:
  auto_reconnect_serial: true
  serial_reconnect_delay: 5
  max_serial_reconnect_attempts: 10
  
  service_retry_delay: 1
  max_service_retry_attempts: 3
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 60
    half_open_max_calls: 3
  
  ppp_negotiation_timeout: 30
  tcp_connection_cleanup_interval: 60
  orphaned_connection_timeout: 300

development:
  debug_packets: false
  simulate_packet_loss: false
  packet_loss_rate: 0.0
  simulate_latency: false
  artificial_latency_ms: 0
  
  mock_services:
    enabled: false
    echo_port: 7777
    discard_port: 7778